controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

torso_controller:
  ros__parameters:
    joints:
      - torso_joint_b1
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_arm_controller:
  ros__parameters:
    joints:
      - arm_left_joint_1_s
      - arm_left_joint_2_l
      - arm_left_joint_3_e
      - arm_left_joint_4_u
      - arm_left_joint_5_r
      - arm_left_joint_6_b
      - arm_left_joint_7_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - arm_right_joint_1_s
      - arm_right_joint_2_l
      - arm_right_joint_3_e
      - arm_right_joint_4_u
      - arm_right_joint_5_r
      - arm_right_joint_6_b
      - arm_right_joint_7_t
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
